### ISSUE TITLE
empty json files

### ISSUE THREAD

**Issue by AlessandroMecchia** [Matteo-Ferrara/gex-tracker#3]
Hi @Matteo-Ferrara, 
nice project! unfortunately when I enter the ticker to analyze the json file remains empty. should I add the data in the file taken from CBOE? 
thanks

**Comment by Matteo-Ferrara** [comment]
No, as explained in the README you have to first run the main.py file and, once asked, enter the ticker in capital letters.

I just tested the project and can tell you that it works perfectly.

**Comment by AlessandroMecchia** [comment]
@Matteo-Ferrara I created a virtual environment on conda and installed the requirements and the code works correctly, but if I try to enter it as a ticket (e.g. TSLA) it returns this error:

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Matteo-Ferrara** [comment]
I think I found the issue. Try to remove the last underscore in line 37 - that is the requests url. 

The result should be: https://cdn.cboe.com/api/global/delayed_quotes/options/{ticker}.json

Let me know if it fixes the problem for TSLA. I think they changed something with the urls

**Comment by AlessandroMecchia** [comment]
@Matteo-Ferrara thanks for the quick replies! it works! :)
